### ISSUE TITLE
Deserialization of Guava's Optional type fails with 2.7 or later

### ISSUE THREAD

**Issue by komamitsu** [FasterXML/jackson-datatypes-collections#28]
The following code works with version 2.6, but it doesn't work with 2.7 or later.

```
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new GuavaModule());
        JavaType type = mapper.getTypeFactory().constructParametrizedType(Optional.class, Optional.class, String.class);
        JsonNode jsonNode = mapper.readTree("{\"k\":\"hello\"}").get("k");
        System.out.println(String.format(">>>>> %s, %s, %s, %s", type.getClass(), type, jsonNode.getClass(), jsonNode));
        System.out.println(mapper.readValue(jsonNode.traverse(), type).toString());
```

```
>>>>> class com.fasterxml.jackson.databind.type.SimpleType, [simple type, class com.google.common.base.Optional<java.lang.String>], class com.fasterxml.jackson.databind.node.TextNode, "hello"
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.google.common.base.Optional` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2330)
```

I guess this delete https://github.com/FasterXML/jackson-datatype-guava/commit/85e894e8a211a7107230054b812e5d0b8dde34f2#diff-49f8660695e4a3f0da79d80faf35e1e7L249 is related to it.

My questions are:
- Is this behaviour expected?
- Is there any workaround?

**Comment by cowtowncoder** [comment]
`Optional` should work, and there are a few unit tests to back it up. I am guessing that in your case problem is construction of `JavaType`:

JavaType type = mapper.getTypeFactory().constructParametrizedType(Optional.class, Optional.class, String.class);

which somehow does not result in proper type: it should be `ReferenceType`, starting with 2.7; earlier it would have been just `SimpleType`.

So question would be if there is something wrong with type resolution. You can try this with

    type = mapper.getTypeFactory().constructType(new TypeReference<Optional<String>>() { });

which should work.

**Comment by komamitsu** [comment]
Thanks! That works.

**Comment by cowtowncoder** [comment]
@komamitsu Ok good. I don't know why the other approach does not -- I think it should.
I will actually reopen this for now so I can have a look.

Thank you for reporting the issue.

**Comment by cowtowncoder** [comment]
Actually not sure if there is anything to do here, so will close -- may be refiled if there is a problem.
