### ISSUE TITLE
Failure of DeserializerTest.pairTyped()

### ISSUE THREAD

**Issue by leventov** [FasterXML/jackson-datatypes-collections#52]
In this test, the pair gets serialized with key and value reversed:
```
DeserializerTest.pairTyped:646 expected:<{"[one":{"@c":".DeserializerTest$B"},"two":5]}> but was:<{"[two":5,"one":{"@c":".DeserializerTest$B"}]}>
```

What I've found so far:

- The test doesn't fail in debug mode (when debugged from within IDE), only in "production" mode (e. g. when Maven tests are run)
- The test doesn't fail when it is run alone, only when it is run together with other tests (in that class and module)
- The test doesn't fail when run on Java 8 runtime, only when run on Java 11 runtime.

Debug printing has led me (so far) to this place in `POJOPropertiesCollector`:
https://github.com/FasterXML/jackson-databind/blob/b12fab11ce477837be0f90d3f21348bafae9e4f5/src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java#L280-L286

When the key and the value get deserialized in the wrong order, `props` are empty after `_addFields()`, but are get populated with [two, one] in `_addMethods()`. In normal cases, [one, two] appear in `props` map already after `_addFields()`.

I had a hypothesis that custom `makeProperties()` logic is silently not get called in `PairInstantiators`. I've found that `findValueInstantiator()` gets called not only with `ObjectIntPair` (for example) as `beanClass`, but also with `ObjectIntPairImpl`. [In my branch](https://github.com/leventov/jackson-datatypes-collections/tree/primitive-collections-base), I've tried to add the following line in `PairInstantiatorsPopulator`:
```java
         PairInstantiators.add(ObjectShortPair.class, objectShortPairLambda);
+        PairInstantiators.add(ObjectShortPairImpl.class, objectShortPairLambda);
```

Which led to an interesting exception:
```
java.lang.NullPointerException
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector._findStdTypeDesc(BasicClassIntrospector.java:226)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forClassAnnotations(BasicClassIntrospector.java:160)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forClassAnnotations(BasicClassIntrospector.java:16)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.introspectClassAnnotations(MapperConfig.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.introspectClassAnnotations(DeserializationContext.java:471)
	at com.fasterxml.jackson.databind.DeserializationContext.findTypeDeserializer(DeserializationContext.java:564)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.pair.PairInstantiators.makeProperties(PairInstantiators.java:180)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.pair.PairInstantiators$4.getFromObjectArguments(PairInstantiators.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:458)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:233)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:135)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:418)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:357)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:271)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:251)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:150)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:527)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase._findSubclassDeserializer(BeanDeserializerBase.java:1627)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handlePolymorphic(BeanDeserializerBase.java:1576)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:602)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1243)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:481)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:201)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2302)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1409)
	at com.fasterxml.jackson.datatype.eclipsecollections.DeserializerTest.primitivePairs(DeserializerTest.java:626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

FYI @cowtowncoder @yawkat

**Comment by cowtowncoder** [comment]
Ok, which datatype package? (I use labels to indicate that)

**Comment by yawkat** [comment]
These tests are a bit too harsh: https://github.com/FasterXML/jackson-datatypes-collections/blob/master/eclipse-collections/src/test/java/com/fasterxml/jackson/datatype/eclipsecollections/DeserializerTest.java#L629-L652 - they could allow changing property order

still a bit weird that it broke now

**Comment by cowtowncoder** [comment]
Fixed as per above PR
