### ISSUE TITLE
Exception using eclipse collection serialization

### ISSUE THREAD

**Issue by goldbal330** [FasterXML/jackson-datatypes-collections#76]
the following test crashes with 

java.lang.IllegalArgumentException: Null JavaType passed

	at com.fasterxml.jackson.databind.deser.DeserializerCache._findCachedDeserializer(DeserializerCache.java:205)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:139)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:458)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.BaseCollectionDeserializer$Ref.createContextual(BaseCollectionDeserializer.java:300)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:696)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:496)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4711)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4520)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)

=================================

@Test
    void testJsonSerialization() throws JsonProcessingException
    {
        MutableList<String> mutableList = Lists.mutable.of("one", "two", "three");
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new EclipseCollectionsModule());

        String valueAsString = objectMapper.writeValueAsString(mutableList);
        MutableList mutableListCopy = objectMapper.readValue(valueAsString, MutableList.class);
        Verify.assertEquals(mutableList, mutableListCopy);
    }

Dependency used is:

 <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-eclipse-collections</artifactId>
            <version>2.11.2</version>
 </dependency>

Please, advise.
Thanks.

**Comment by yawkat** [comment]
This was fixed in 0d451d68c2e6b3bf6cca86600ea780810bc0e1b1 . Please do not use raw collection types until that fix has been released. Or even better, don't use them at all :)

An example of how to use the proper generic types is given here: https://github.com/eclipse/eclipse-collections/blob/master/docs/jackson.md#serializing-directly
